/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sht1xSensor */

#ifndef _Included_Sht1xSensor
#define _Included_Sht1xSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sht1xSensor
 * Method:    getTemperatureInFahrenheit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Sht1xSensor_getTemperatureInFahrenheit
  (JNIEnv *, jobject);

/*
 * Class:     Sht1xSensor
 * Method:    getTemperatureInCelcius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Sht1xSensor_getTemperatureInCelcius
  (JNIEnv *, jobject);

/*
 * Class:     Sht1xSensor
 * Method:    getHumidity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Sht1xSensor_getHumidity
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
